In [51]:
import pandas as pd
import numpy as np

In [1]:


df=pd.read_csv("turboAzInfoCleanedData.csv")

In [13]:
Marka=df['Marka'].unique()

In [14]:
Marka.sort()

In [15]:
Marka

array(['Abarth', 'Alfa Romeo', 'Audi', 'BMW', 'BYD', 'Baic', 'Bajaj',
       'Bentley', 'Bestune', 'Brilliance', 'Cadillac', 'Changan', 'Chery',
       'Chevrolet', 'Chrysler', 'Citroen', 'DAF', 'Dacia', 'Daewoo',
       'Dayun', 'Dnepr', 'Dodge', 'DongFeng', 'FAW', 'Fiat', 'Ford',
       'Foton', 'GAC', 'GAZ', 'GMC', 'Geely', 'Great Wall', 'HOWO',
       'Haima', 'Haojue', 'Harley-Davidson', 'Haval', 'Honda', 'Hongqi',
       'Hummer', 'Hyundai', 'IJ', 'Infiniti', 'Iran Khodro', 'Isuzu',
       'Iveco', 'JAC', 'Jaguar', 'Jeep', 'Jetour', 'KAIYI', 'KamAz',
       'Kawasaki', 'Kayo', 'Khazar', 'Kia', 'Kuba', 'LADA (VAZ)',
       'Lamborghini', 'Land Rover', 'Lexus', 'Lifan', 'Lincoln', 'LuAz',
       'MAN', 'MAZ', 'MG', 'Mack', 'Maserati', 'Mazda', 'McLaren',
       'Mercedes', 'Mercedes-Maybach', 'Mini', 'Minsk', 'Mitsubishi',
       'Moskvich', 'Muravey', 'Nissan', 'Opel', 'PAZ', 'Peugeot',
       'Polaris', 'Polestar', 'Porsche', 'RKS', 'Ravon', 'Renault',
       'Rolls-Royce', 'Rover', 'SEAT', 'Saab', 'Saipa', 'Saturn',
       'Scania', 'Scion', 'Shacman', 'Skoda', 'Skyline', 'Skywell',
       'Smart', 'Soueast', 'Ssang Yong', 'Subaru', 'Suzuki', 'Tofas',
       'Toyota', 'Tufan', 'UAZ', 'Ural', 'Volkswagen', 'Volvo', 'Wuling',
       'Yamaha', 'ZAZ', 'ZIL', 'ZX Auto', 'Zeekr', 'Zontes'], dtype=object)

In [17]:
marka_list=Marka.tolist()

In [18]:
marka_list

['Abarth',
 'Alfa Romeo',
 'Audi',
 'BMW',
 'BYD',
 'Baic',
 'Bajaj',
 'Bentley',
 'Bestune',
 'Brilliance',
 'Cadillac',
 'Changan',
 'Chery',
 'Chevrolet',
 'Chrysler',
 'Citroen',
 'DAF',
 'Dacia',
 'Daewoo',
 'Dayun',
 'Dnepr',
 'Dodge',
 'DongFeng',
 'FAW',
 'Fiat',
 'Ford',
 'Foton',
 'GAC',
 'GAZ',
 'GMC',
 'Geely',
 'Great Wall',
 'HOWO',
 'Haima',
 'Haojue',
 'Harley-Davidson',
 'Haval',
 'Honda',
 'Hongqi',
 'Hummer',
 'Hyundai',
 'IJ',
 'Infiniti',
 'Iran Khodro',
 'Isuzu',
 'Iveco',
 'JAC',
 'Jaguar',
 'Jeep',
 'Jetour',
 'KAIYI',
 'KamAz',
 'Kawasaki',
 'Kayo',
 'Khazar',
 'Kia',
 'Kuba',
 'LADA (VAZ)',
 'Lamborghini',
 'Land Rover',
 'Lexus',
 'Lifan',
 'Lincoln',
 'LuAz',
 'MAN',
 'MAZ',
 'MG',
 'Mack',
 'Maserati',
 'Mazda',
 'McLaren',
 'Mercedes',
 'Mercedes-Maybach',
 'Mini',
 'Minsk',
 'Mitsubishi',
 'Moskvich',
 'Muravey',
 'Nissan',
 'Opel',
 'PAZ',
 'Peugeot',
 'Polaris',
 'Polestar',
 'Porsche',
 'RKS',
 'Ravon',
 'Renault',
 'Rolls-Royce',
 'Rover',
 'SEAT',
 'Saab',
 'Saipa',
 'Saturn',
 'Scania',
 'Scion',
 'Shacman',
 'Skoda',
 'Skyline',
 'Skywell',
 'Smart',
 'Soueast',
 'Ssang Yong',
 'Subaru',
 'Suzuki',
 'Tofas',
 'Toyota',
 'Tufan',
 'UAZ',
 'Ural',
 'Volkswagen',
 'Volvo',
 'Wuling',
 'Yamaha',
 'ZAZ',
 'ZIL',
 'ZX Auto',
 'Zeekr',
 'Zontes']

In [27]:
LR=df[df['Marka']=='Land Rover']

In [30]:
length(LR['Model']=='Velar')

NameError: name 'length' is not defined

In [33]:
df['Rəng'].unique()

array(['Ağ', 'Boz', 'Qara', 'Yaş Asfalt', 'Gümüşü', 'Göy', 'Tünd qırmızı',
       'Bej', 'Qırmızı', 'Mavi', 'Qəhvəyi', 'Sarı', 'Qızılı', 'Yaşıl',
       'Narıncı', 'Bənövşəyi', 'Çəhrayı'], dtype=object)

In [45]:
menu=df['Marka'][2]

In [46]:
path='logo/'+menu +'.png'

In [47]:
print(path)

logo/Mercedes.png

In [48]:
df['Marka'].sort_values().unique()

array(['Abarth', 'Alfa Romeo', 'Audi', 'BMW', 'BYD', 'Baic', 'Bajaj',
       'Bentley', 'Bestune', 'Brilliance', 'Cadillac', 'Changan', 'Chery',
       'Chevrolet', 'Chrysler', 'Citroen', 'DAF', 'Dacia', 'Daewoo',
       'Dayun', 'Dnepr', 'Dodge', 'DongFeng', 'FAW', 'Fiat', 'Ford',
       'Foton', 'GAC', 'GAZ', 'GMC', 'Geely', 'Great Wall', 'HOWO',
       'Haima', 'Haojue', 'Harley-Davidson', 'Haval', 'Honda', 'Hongqi',
       'Hummer', 'Hyundai', 'IJ', 'Infiniti', 'Iran Khodro', 'Isuzu',
       'Iveco', 'JAC', 'Jaguar', 'Jeep', 'Jetour', 'KAIYI', 'KamAz',
       'Kawasaki', 'Kayo', 'Khazar', 'Kia', 'Kuba', 'LADA (VAZ)',
       'Lamborghini', 'Land Rover', 'Lexus', 'Lifan', 'Lincoln', 'LuAz',
       'MAN', 'MAZ', 'MG', 'Mack', 'Maserati', 'Mazda', 'McLaren',
       'Mercedes', 'Mercedes-Maybach', 'Mini', 'Minsk', 'Mitsubishi',
       'Moskvich', 'Muravey', 'Nissan', 'Opel', 'PAZ', 'Peugeot',
       'Polaris', 'Polestar', 'Porsche', 'RKS', 'Ravon', 'Renault',
       'Rolls-Royce', 'Rover', 'SEAT', 'Saab', 'Saipa', 'Saturn',
       'Scania', 'Scion', 'Shacman', 'Skoda', 'Skyline', 'Skywell',
       'Smart', 'Soueast', 'Ssang Yong', 'Subaru', 'Suzuki', 'Tofas',
       'Toyota', 'Tufan', 'UAZ', 'Ural', 'Volkswagen', 'Volvo', 'Wuling',
       'Yamaha', 'ZAZ', 'ZIL', 'ZX Auto', 'Zeekr', 'Zontes'], dtype=object)

In [49]:
df

,Unnamed: 0,Şəhər,Marka,Model,İl,Ban Növü,Rəng,Mühərrik,Mühərrikin gücü,Yanacaq növü,Yürüş,Sürətlər qutusu,Ötürücü,Yeni,Qiymət
0,0,Sumqayıt,Nissan,Tiida,2012,Sedan,Ağ,1.5,109,Benzin,53235,Avtomat,Ön,Xeyr,14900
1,1,Bakı,Haval,H6,2022,Offroader / SUV,Ağ,1.5,243,Hibrid,0,Avtomat,Ön,Bəli,58900
2,2,Bakı,Mercedes,E 220,2012,Sedan,Ağ,2.2,170,Dizel,208000,Avtomat,Arxa,Xeyr,33800
3,3,Bakı,Renault,Kaptur,2021,Offroader / SUV,Ağ,1.6,114,Benzin,0,Avtomat,Ön,Bəli,39780
4,4,Bakı,BMW,X6 M,2010,Offroader / SUV,Boz,4.4,555,Benzin,210000,Avtomat,Tam,Xeyr,37060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,14395,Lənkəran,LADA (VAZ),2106,1991,Sedan,Bej,1.6,75,Benzin,37707,Mexaniki,Arxa,Xeyr,2900
14394,14396,Bakı,Mitsubishi,Pajero,1995,Offroader / SUV,Gümüşü,2.8,125,Dizel,447504,Avtomat,Tam,Xeyr,11500
14395,14397,Bakı,Toyota,Prado,2007,Offroader / SUV,Qara,4.0,249,Benzin,206500,Avtomat,Arxa,Xeyr,35000
14396,14398,Bakı,Opel,Astra,2007,Hetçbek,Boz,1.4,90,Benzin,178000,Mexaniki,Ön,Xeyr,12500
14397,14399,Bakı,Hyundai,Accent,2006,Sedan,Qara,1.5,110,Dizel,151000,Mexaniki,Ön,Xeyr,12300

In [57]:
np.arange(0, 7, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9])

In [55]:
round(1.78655,2)

1.79

In [62]:
engine_size=[]
for size in np.arange(0,7000,100):
    engine_size.append(size/100)
engine_size

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0]